### ISSUE TITLE
TypeError: Do not know how to serialize `BigInt`

### ISSUE THREAD

**Issue by Hazeman28** [prisma/studio#756]
#### 2. Logs from Developer Tools Console or Command line, if any:

<details>
<summary>Error details</summary>

```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at new xo (http://localhost:5555/assets/index.js:1:235406)
    at fs (http://localhost:5555/assets/vendor.js:23:50060)
    at Fa (http://localhost:5555/assets/vendor.js:23:67523)
    at fl (http://localhost:5555/assets/vendor.js:23:105725)
    at au (http://localhost:5555/assets/vendor.js:23:97158)
    at iu (http://localhost:5555/assets/vendor.js:23:97083)
    at Xl (http://localhost:5555/assets/vendor.js:23:94112)
    at http://localhost:5555/assets/vendor.js:23:45715
    at t.unstable_runWithPriority (http://localhost:5555/assets/vendor.js:14:9482)
    at Vi (http://localhost:5555/assets/vendor.js:23:45424)
    at ji (http://localhost:5555/assets/vendor.js:23:45660)
    at Bi (http://localhost:5555/assets/vendor.js:23:45595)
    at Yl (http://localhost:5555/assets/vendor.js:23:90893)
    at Object.enqueueForceUpdate (http://localhost:5555/assets/vendor.js:23:49700)
    at t.P.forceUpdate (http://localhost:5555/assets/vendor.js:14:863)
    at http://localhost:5555/assets/vendor.js:382:28425
    at o (http://localhost:5555/assets/vendor.js:59:57741)
```

</details>

#### 3. Does the issue persist even after updating to the latest `prisma` alpha? (`npm i -D @prisma/cli@dev`)

**Yes, it does.**

#### 4. Prisma schema (if relevant):

<details>
<summary>Prisma schema</summary>

```prisma
model TournamentPrize {
  id                BigInt                       @id @default(autoincrement())
  createdAt         DateTime                     @default(now()) @map(name: "created_at") @db.Timestamp(6)
  updatedAt         DateTime                     @default(now()) @updatedAt @map("updated_at") @db.Timestamptz(6)
  customTypeId      BigInt?                      @map(name: "custom_type_id")
  customType        TournamentCustomPrizeType?   @relation(fields: [customTypeId], references: [id])
  currencyId        BigInt?                      @map(name: "currency_id")
  currency          Currency?                    @relation(fields: [currencyId], references: [id])
  type              TournamentPrizeType
  placementType     TournamentPrizePlacementType @map(name: "placement_type")
  quantity          Int
  placement         Int[]
  state             TournamentPrizeState         @default(CREATED)
  tournamentId      BigInt                       @map(name: "tournament_id")
  tournament        Tournament                   @relation(fields: [tournamentId], references: [id])
  tournamentStageId BigInt?
  tournamentStage   TournamentStage?             @relation(fields: [tournamentStageId], references: [id])
  winners           TournamentTeam[]
  actionHistory     TournamentPrizeAction[]

  @@map(name: "tournament_prizes")
}

model TournamentTeam {
  id            BigInt                  @id @default(autoincrement())
  createdAt     DateTime                @default(now()) @map(name: "created_at") @db.Timestamp(6)
  updatedAt     DateTime                @default(now()) @updatedAt @map("updated_at") @db.Timestamptz(6)
  tournamentId  BigInt                  @map(name: "game_tournament_id")
  name          String
  players       Json?
  contact       String
  isManager     Boolean?                @map(name: "is_manager")
  schedule      String?
  extra         String?
  discord       String?
  pending       Boolean?                @default(false)
  state         Int?                    @default(1)
  fixedOrder    Int?                    @map(name: "fixed_order")
  ownerId       BigInt?                 @map(name: "owner")
  manager       Json?
  custom        Json?
  teamId        BigInt?                 @map(name: "team_id")
  tournament    Tournament              @relation(fields: [tournamentId], references: [id])
  owner         User?                   @relation(fields: [ownerId], references: [id])
  team          Team?                   @relation(fields: [teamId], references: [id])
  teamAMatches  TournamentMatch[]       @relation(name: "TournamentTeamA")
  teamBMatches  TournamentMatch[]       @relation(name: "TournamentTeamB")
  invitations   TeamInvitation[]
  claimedPrizes TournamentPrize[]
  prizeActions  TournamentPrizeAction[]

  @@unique([tournamentId, name], name: "game_tournament_teams_game_tournament_id_name_key")
  @@map(name: "game_tournament_teams")
}
```

</details>

### Additional info

Error occurred during an attempt to display info of a relation field `winners` on the `TournamentPrize` model. Same happens with other relation fields, since all of our models use BigInt for the id column.

**Comment by madebysid** [comment]
Hey @Hazeman28, thanks for reporting this! This used to be an issue, but I fixed it a while ago. Can you check your browser's DevTools for a log that displays Studio's version? What does it say? Can you also run `prisma -v` in your terminal and check Studio's version there?

Although you're on the latest Prisma CLI release, I want to eliminate the possibility of an older Studio version (which would be a bug/accidental)

**Comment by Hazeman28** [comment]
> Hey @Hazeman28, thanks for reporting this! This used to be an issue, but I fixed it a while ago. Can you check your browser's DevTools for a log that displays Studio's version? What does it say? Can you also run `prisma -v` in your terminal and check Studio's version there?
> 
> Although you're on the latest Prisma CLI release, I want to eliminate the possibility of an older Studio version (which would be a bug/accidental)

Hi @madebysid, dev tools show:
```
Studio version 0.417.0
```
Same version is displayed in terminal when running `prisma -v`.

**Comment by nshusr** [comment]
TypeError: Do not know how to serialize a BigInt

Please fix this problem, add the following code  https://github.com/prisma/studio/issues/614#issuecomment-795213237
```
BigInt.prototype.toJSON = function() {       
  return this.toString()
}
```

**Comment by madebysid** [comment]
Hey peeps, Studio already does this, so I'm confused why you're only just seeing this. OP was on a pretty old Prisma version, which might have been the culprit. Are you all on the latest Prisma version (3.5.0 as of writing)? I don't believe this should happen there.

**Comment by Hazeman28** [comment]
> Hey peeps, Studio already does this, so I'm confused why you're only just seeing this. OP was on a pretty old Prisma version, which might have been the culprit. Are you all on the latest Prisma version (3.5.0 as of writing)? I don't believe this should happen there.

@madebysid same issue on `3.5.0`.

<details>
<summary>

```bash
npx prisma -v
```
</summary>

```
npx prisma -v                  
Environment variables loaded from .env
prisma                  : 3.5.0
@prisma/client          : 3.5.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt 78a5df6def6943431f4c022e1428dbc3e833cf8e (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : 78a5df6def6943431f4c022e1428dbc3e833cf8e
Studio                  : 0.439.0
```
</details>

**Comment by aaronstarkey** [comment]
still seeing this with 3.6.0 and express 14.7.1

```⇒  npx prisma -v
Environment variables loaded from .env
prisma                  : 3.6.0
@prisma/client          : 3.6.0
Current platform        : darwin
Query Engine (Node-API) : libquery-engine dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt dc520b92b1ebb2d28dc3161f9f82e875bd35d727 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : dc520b92b1ebb2d28dc3161f9f82e875bd35d727
Studio                  : 0.440.0```

**Comment by madebysid** [comment]
Hey everyone, thanks for confirming this, I'll take a look as soon as I can

**Comment by madebysid** [comment]
I've just fixed this and it will be out in tomorrow's Prisma CLI release. When it lands, I'd really appreciate it if someone could try upgrading and verify if you're able to work with `BigInt`s again. If not, I'll reopen and take another look.

Thanks for being patient!

**Comment by Danishap07** [comment]
Even I am facing the same issue right now guys...

**Comment by kiloz** [comment]
I am facing `TypeError: Do not know how to serialize a BigInt` issue.

file: schema.prisma
```
model xyz {
...
created              BigInt      @db.BigInt                     //1465371124000,
...
}
```
Please advise any work arounds, if they exist.

```
$ npx prisma -v
prisma                  : 3.9.2
@prisma/client          : 3.9.2
Current platform        : darwin
Query Engine (Node-API) : libquery-engine bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/libquery_engine-darwin.dylib.node)
Migration Engine        : migration-engine-cli bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/migration-engine-darwin)
Introspection Engine    : introspection-core bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/introspection-engine-darwin)
Format Binary           : prisma-fmt bcc2ff906db47790ee902e7bbc76d7ffb1893009 (at node_modules/@prisma/engines/prisma-fmt-darwin)
Default Engines Hash    : bcc2ff906db47790ee902e7bbc76d7ffb1893009
Studio                  : 0.457.0
```

**Comment by lelekooo** [comment]
I am facing: `Do not know how to serialize a BigInt` issue in the prisma studio.
When I'm trying to find some entity by id, and the id is a BigInt.
The search is not executed and if you open the browser console you able to see this error:
``` 
Uncaught TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at _t.serialize (index.js:1:49091)
    at _t.update (index.js:1:12197)
    at Cc (vendor.js:50:6994)
    at _t.n (vendor.js:50:6688)
    at _t.update (index.js:1:48948)
    at Cc (vendor.js:50:6994)
    at _t.n (vendor.js:50:6688)
    at ra.handleChangeField (index.js:1:98910)
    at onSelect (index.js:1:101101)
 ```


my prisma version is: 
 ```
 $ prisma -v                                                                                                                     

prisma                  : 3.11.0
@prisma/client          : 3.11.0
Current platform        : darwin-arm64
Query Engine (Node-API) : libquery-engine b371888aaf8f51357c7457d836b86d12da91658b (at ../../../../../.nvm/versions/node/v16.14.0/lib/node_modules/prisma/node_modules/@prisma/engines/libquery_engine-darwin-arm64.dylib.node)
Migration Engine        : migration-engine-cli b371888aaf8f51357c7457d836b86d12da91658b (at ../../../../../.nvm/versions/node/v16.14.0/lib/node_modules/prisma/node_modules/@prisma/engines/migration-engine-darwin-arm64)
Introspection Engine    : introspection-core b371888aaf8f51357c7457d836b86d12da91658b (at ../../../../../.nvm/versions/node/v16.14.0/lib/node_modules/prisma/node_modules/@prisma/engines/introspection-engine-darwin-arm64)
Format Binary           : prisma-fmt b371888aaf8f51357c7457d836b86d12da91658b (at ../../../../../.nvm/versions/node/v16.14.0/lib/node_modules/prisma/node_modules/@prisma/engines/prisma-fmt-darwin-arm64)
Default Engines Hash    : b371888aaf8f51357c7457d836b86d12da91658b
Studio                  : 0.458.0
Preview Features        : interactiveTransactions
```

**Comment by srinath-ramanujan** [comment]
Why is the issue closed when more people are still facing the same issue? JSON.stringify does not know how to work with BigInt

**Comment by janpio** [comment]
Because in December 2021 we did something to fix the concrete problem (which was about displaying BigInt data in some models and relation fields), and since then we just had some random comments about other possible problems. If you think you have a problem, please open a **new** issue and fully describe your problem so we can reproduce and then try to fix it. Thanks.
